/******************************************************************************
 *                       Copyright (c) 2008, Jabil Circuit
 *
 * This source code and any compilation or derivative thereof is the sole
 * property of Jabil Circuit and is provided pursuant to a Software License
 * Agreement.  This code is the proprietary information of Jabil Circuit and
 * is confidential in nature.  Its use and dissemination by any party other
 * than Jabil Circuit is strictly limited by the confidential information
 * provisions of the Software License Agreement referenced above.
 *
 ******************************************************************************
 *
 * Project      : WaterOptimizer Irrigation System (WOIS)
 * Organization : WaterOptimizer, LLC
 * Module       : global.h
 * Description  : This file defines global types and manifest constants.
 *
 *****************************************************************************/

#ifndef __global_H
#define __global_H

/* MODULE global */

/* Compute the byte-offset of a member in a structure. */
//#ifndef woffsetof
#define woffsetof(TYPE,MEMBER)   ((size_t)&((TYPE *)0)->MEMBER)
//#endif

#ifdef WIN32

/*
 * System-wide type definitions
 */

typedef unsigned char       uint8_t;
typedef signed char         int8_t;
typedef unsigned short      uint16_t;
typedef signed short        int16_t;
typedef unsigned long       uint32_t;
typedef signed long         int32_t;
typedef unsigned long long  uint64_t;
typedef signed long long    int64_t;
typedef signed int          sint_t;
typedef unsigned int        uint_t;
typedef unsigned char       bool_t;

#else /* !WIN32 */

/* Include header files auto-generated by the Processor Expert utility */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include <null.h>

typedef unsigned long long uint64_t;
typedef signed long long int64_t;

typedef signed int   sint_t;
typedef unsigned int uint_t;

typedef bool bool_t;
#define false FALSE
#define true TRUE

#endif /* !WIN32 */

/* END global */

#endif
