/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwAdc.C
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : ADC
**     Version   : Bean 01.452, Driver 01.21, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 7/12/2011, 1:59 PM
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings  :
**         AD control register         : ADCSC1      [0xFFFF8010]
**         AD control register         : ADCCFG      [0xFFFF8016]
**         AD control register         : ADCRH       [0xFFFF8012]
**         AD control register         : ADCRL       [0xFFFF8013]
**         AD control register         : ADCCVH      [0xFFFF8014]
**         AD control register         : ADCCVL      [0xFFFF8015]
**         AD control register         : ADCSC2      [0xFFFF8011]
**         AD control register         : APCTL1      [0xFFFF8017]
**         AD control register         : APCTL2      [0xFFFF8018]
**         AD control register         : APCTL3      [0xFFFF8019]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         User handling procedure     : not specified
**         Number of conversions       : 8
**         AD resolution               : 12-bit
**
**         Input pins
**
**              Port name              : PTF
**              Bit number (in port)   : 2
**              Bit mask of the port   : 0x0004
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 3
**              Bit mask of the port   : 0x0008
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 4
**              Bit mask of the port   : 0x0010
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 5
**              Bit mask of the port   : 0x0020
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 6
**              Bit mask of the port   : 0x0040
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 7
**              Bit mask of the port   : 0x0080
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTG
**              Bit number (in port)   : 2
**              Bit mask of the port   : 0x0004
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**              Port name              : PTG
**              Bit number (in port)   : 3
**              Bit mask of the port   : 0x0008
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**              Port name              : PTG
**              Bit number (in port)   : 4
**              Bit mask of the port   : 0x0010
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**              Port name              : PTG
**              Bit number (in port)   : 5
**              Bit mask of the port   : 0x0020
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**              Port name              : PTG
**              Bit number (in port)   : 6
**              Bit mask of the port   : 0x0040
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**              Port name              : PTG
**              Bit number (in port)   : 7
**              Bit mask of the port   : 0x0080
**              Port data register     : PTGD        [0xFFFF801C]
**              Port control register  : PTGDD       [0xFFFF801D]
**
**         Initialization:
**              Conversion             : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-8
**     Contents  :
**         Enable         - byte hwAdc_Enable(void);
**         Disable        - byte hwAdc_Disable(void);
**         MeasureChan    - byte hwAdc_MeasureChan(bool WaitForResult, byte Channel);
**         GetChanValue16 - byte hwAdc_GetChanValue16(byte Channel, word *Value);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE hwAdc. */

#include "hwAdc.h"



static void hwAdc_MainMeasure(void);
/*
** ===================================================================
**     Method      :  MainMeasure (bean ADC)
**
**     Description :
**         The method performs the conversion of the input channels in 
**         the polling mode.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define STOP            0              /* STOP state           */
#define MEASURE         1              /* MESURE state         */
#define CONTINUOUS      2              /* CONTINUOS state      */
#define SINGLE          3              /* SINGLE state         */

static const  word Table[12] = {0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80,0x0100,0x0200,0x0400,0x0800
};  /* Table of mask constants */

static const  byte Channels[12] = {0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17
};  /* Contents for the device control register */

static bool EnUser;                    /* Enable/Disable device */
static bool EnMode;                    /* Enable/Disable device in speed mode */
static word OutFlg;                    /* Measurement finish flags */
static byte SumChan;                   /* Number of measured channels */
static byte ModeFlg;                   /* Current state of device */

word hwAdc_OutV[12];                   /* Sum of measured values */





/*
** ===================================================================
**     Method      :  MainMeasure (bean ADC)
**
**     Description :
**         The method performs the conversion of the input channels in 
**         the polling mode.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void hwAdc_MainMeasure(void)
{
  byte SumCnt;                         /* Number of measured channels */
  TWREG tmpTwreg;

  for (SumCnt=0; SumCnt<8; SumCnt++) {
    ADCSC1 = Channels[SumChan];        /* Start measurement of next channel */
    while (!ADCSC1_COCO) {}            /* Wait for AD conversion complete */
    tmpTwreg.b.high = ADCRH;
    tmpTwreg.b.low = ADCRL;
    hwAdc_OutV[SumChan] += tmpTwreg.w; /* Save measured value */
  }
  OutFlg |= Table[SumChan];            /* Value of measured channel is available */
  ModeFlg = STOP;                      /* Set the device to the stop mode */
}
/*
** ===================================================================
**     Method      :  hwAdc_HWEnDi (bean ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwAdc_HWEnDi(void)
{
  if (EnUser && EnMode) {              /* Enable device? */
    if (ModeFlg) {                     /* Start or stop measurement? */
      OutFlg &= ~Table[SumChan];       /* Output value isn't available */
      hwAdc_OutV[SumChan] = 0;         /* Set variable for storing measured values to 0 */
      hwAdc_MainMeasure();
    }
  }
  else {
    ADCSC1 = 0x1F;                     /* Disable the device */
  }
}

/*
** ===================================================================
**     Method      :  hwAdc_SetHigh (bean ADC)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the High speed mode. The method is 
**         called automatically as s part of the CPU SetHighSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwAdc_SetHigh(void)
{
  EnMode = TRUE;                       /* Set the flag "device enabled" in the actual speed CPU mode */
  hwAdc_HWEnDi();                      /* Enable/disable device according to the status flags */
}

/*
** ===================================================================
**     Method      :  hwAdc_SetSlow (bean ADC)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the Slow speed mode. The method is 
**         called automatically as a part of the CPU SetSlowSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwAdc_SetSlow(void)
{
  EnMode = FALSE;                      /* Set the flag "device disabled" in the actual speed CPU mode */
  hwAdc_HWEnDi();                      /* Enable/disable device according to the status flags */
}

/*
** ===================================================================
**     Method      :  hwAdc_Enable (bean ADC)
**
**     Description :
**         Enables A/D converter bean. <Events> may be generated
**         (<DisableEvent>/<EnableEvent>). If possible, this method
**         switches on A/D converter device, voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte hwAdc_Enable(void)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (EnUser) {                        /* Is the device enabled by user? */
    return ERR_OK;                     /* If yes then set the flag "device enabled" */
  }
  EnUser = TRUE;                       /* Set the flag "device enabled" */
  hwAdc_HWEnDi();                      /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwAdc_Disable (bean ADC)
**
**     Description :
**         Disables A/D converter bean. No <events> will be generated.
**         If possible, this method switches off A/D converter device,
**         voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte hwAdc_Disable(void)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_OK;                     /* If yes then OK */
  }
  EnUser = FALSE;                      /* If yes then set the flag "device disabled" */
  hwAdc_HWEnDi();                      /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwAdc_MeasureChan (bean ADC)
**
**     Description :
**         This method performs measurement on one channel. (Note: If
**         the <number of conversions> is more than one the conversion
**         of the A/D channel is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of
**                           conversion. If the <interrupt service> is
**                           disabled and at the same time a <number of
**                           conversions> is greater than 1, the
**                           WaitForResult parameter is ignored and the
**                           method waits for each result every time.
**         Channel         - Channel number. If only one
**                           channel in the bean is set this parameter
**                           is ignored, because the parameter is set
**                           inside this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
**                           ERR_RANGE - Parameter "Channel" out of range
** ===================================================================
*/
byte PE_hwAdc_MeasureChan(byte Channel)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (Channel >= 12) {                 /* Is channel number greater than or equal to 12 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = SINGLE;                    /* Set state of device to the measure mode */
  SumChan = Channel;                   /* Set required channel */
  hwAdc_HWEnDi();                      /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwAdc_GetChanValue16 (bean ADC)
**
**     Description :
**         This method returns the last measured value of the required
**         channel justified to the left. Compared with <GetChanValue>
**         method this method returns more accurate result if the
**         <number of conversions> is greater than 1 and <AD resolution>
**         is less than 16 bits. In addition, the user code dependency
**         on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the bean is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte hwAdc_GetChanValue16(byte Channel,word *Value)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (Channel >= 12) {                 /* Is channel number greater than or equal to 12 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (!(OutFlg & Table[Channel])) {    /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Value = (word)((hwAdc_OutV[Channel]) << 1); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwAdc_Init (bean ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwAdc_Init(void)
{
  EnUser = TRUE;                       /* Enable device */
  OutFlg = 0;                          /* No measured value */
  SumChan = 0;
  ModeFlg = STOP;                      /* Device isn't running */
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0,??=0,??=0,??=0,??=0 */
  setReg8(ADCSC2, 0x00);               /* Disable HW trigger and autocompare */ 
  /* ADCCFG: ADLPC=0,ADIV1=1,ADIV0=1,ADLSMP=1,MODE1=0,MODE0=1,ADICLK1=0,ADICLK0=1 */
  setReg8(ADCCFG, 0x75);               /* Set prescaler bits */ 
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=1,ADCH3=1,ADCH2=1,ADCH1=1,ADCH0=1 */
  setReg8(ADCSC1, 0x1F);               /* Disable the module */ 
  hwAdc_SetHigh();                     /* Initial speed CPU mode is high */
}


/* END hwAdc. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
