/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwBusData.H
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : ByteIO
**     Version   : Bean 02.055, Driver 03.08, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 5/14/2010, 1:20 PM
**     Abstract  :
**         This bean "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Comment   :
**         TODO...
**         
**         Notes:
**           - Direction is set to output mode except for when input operations are in progress.
**     Settings  :
**         Port name                   : PTJ
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         8-bit data register         : PTJD      [0xFFFF802E]
**         8-bit control register      : PTJDD     [0xFFFF802F]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    55   |   PTJ0
**                    1      |    54   |   PTJ1
**                    2      |    44   |   PTJ2
**                    3      |    43   |   PTJ3
**                    4      |    32   |   PTJ4
**                    5      |    31   |   PTJ5
**                    6      |    30   |   PTJ6
**                    7      |    29   |   PTJ7
**             ----------------------------------------------------
**     Contents  :
**         SetInput  - void hwBusData_SetInput(void);
**         SetOutput - void hwBusData_SetOutput(void);
**         GetVal    - byte hwBusData_GetVal(void);
**         PutVal    - void hwBusData_PutVal(byte Val);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef hwBusData_H_
#define hwBusData_H_

/* MODULE hwBusData. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "hwCpu.h"


/*
** ===================================================================
**     Method      :  hwBusData_GetVal (bean ByteIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
#define hwBusData_GetVal() ( \
    getReg8(PTJD)                      /* Evaluate to port data */ \
  )

/*
** ===================================================================
**     Method      :  hwBusData_PutVal (bean ByteIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
#define hwBusData_PutVal(Val) ( \
    (void)setReg8(PTJD, Val)           /* PTJD0-PTJD7=Val[bits 0-7] */ \
  )

/*
** ===================================================================
**     Method      :  hwBusData_SetOutput (bean ByteIO)
**
**     Description :
**         This method sets direction of the bean to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define hwBusData_SetOutput() ( \
    (void)setReg8(PTJDD, 0xFF)         /* PTJDD7=0x01, PTJDD6=0x01, PTJDD5=0x01, PTJDD4=0x01, PTJDD3=0x01, PTJDD2=0x01, PTJDD1=0x01, PTJDD0=0x01 */ \
  )

/*
** ===================================================================
**     Method      :  hwBusData_SetInput (bean ByteIO)
**
**     Description :
**         This method sets direction of the bean to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define hwBusData_SetInput() ( \
    (void)setReg8(PTJDD, 0x00)         /* PTJDD7=0x00, PTJDD6=0x00, PTJDD5=0x00, PTJDD4=0x00, PTJDD3=0x00, PTJDD2=0x00, PTJDD1=0x00, PTJDD0=0x00 */ \
  )



/* END hwBusData. */
#endif /* #ifndef __hwBusData_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
