/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwBusKeypad.C
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : BitsIO
**     Version   : Bean 02.097, Driver 03.08, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 7/12/2011, 1:59 PM
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Output direction only.
**     Settings  :
**         Port name                   : PTC
**
**         Bit mask of the port        : 0x0007
**         Number of bits/pins         : 3
**         Single bit numbers          : 0 to 2
**         Values range                : 0 to 7
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 7 = 007H
**         Initial pull option         : off
**
**         Port data register          : PTCD      [0xFFFF8004]
**         Port control register       : PTCDD     [0xFFFF8005]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    34   |   PTC0_RGPIO8_TPM3CH0
**                    1      |    33   |   PTC1_RGPIO9_TPM3CH1
**                    2      |    25   |   PTC2_RGPIO10_TPM3CH2
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         PutVal - void hwBusKeypad_PutVal(byte Val);
**         SetBit - void hwBusKeypad_SetBit(byte Bit);
**         ClrBit - void hwBusKeypad_ClrBit(byte Bit);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE hwBusKeypad. */

#include "hwBusKeypad.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "hwCpu.h"


/*
** ===================================================================
**     Method      :  hwBusKeypad_GetMsk (bean BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte hwBusKeypad_Table[3] = { /* Table of mask constants */
   0x01, 0x02, 0x04
};

static byte hwBusKeypad_GetMsk (byte PinIndex)
{
  return (byte)(PinIndex<3 ? hwBusKeypad_Table[PinIndex] : 0); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  hwBusKeypad_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void hwBusKeypad_PutVal(byte Val)
{
  Val &= 0x07;                         /* Mask output value */
  setReg8(PTCD, (getReg8(PTCD) & (~0x07)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  hwBusKeypad_ClrBit (bean BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
void hwBusKeypad_ClrBit(byte Bit)
{
  byte const Mask = hwBusKeypad_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8(PTCCLR, Mask);               /* [bit (Bit)]=0x01 */
}

/*
** ===================================================================
**     Method      :  hwBusKeypad_SetBit (bean BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
void hwBusKeypad_SetBit(byte Bit)
{
  byte const Mask = hwBusKeypad_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8(PTCSET, Mask);               /* [bit (Bit)]=0x01 */
}


/* END hwBusKeypad. */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
