/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwCts.C
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : Init_KBI
**     Version   : Bean 01.022, Driver 01.09, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 7/12/2011, 1:59 PM
**     Abstract  :
**          This file implements the KBI (KBI2) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**          The KBI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.
**          The keyboard interrupt module (KBI) provides a few independently maskable 
**          external interrupts. When a port pin is enabled for keyboard interrupt 
**          function, an internal pullup/pulldown device is also enabled on the pin.

**     Settings  :
**          Bean name                                      : hwCts
**          Device                                         : KBI2
**          Settings 
**            Triggering sensitivity                       : edge
**          Pins 
**            Pin0                                         : Disabled
**            Pin1                                         : Enabled
**              Pin                                        : PTD1_KBI2P1_MOSI2
**              Pin signal                                 : XBEE_CTS_N
**            Pin2                                         : Disabled
**            Pin3                                         : Disabled
**            Pin4                                         : Disabled
**            Pin5                                         : Enabled
**              Pin                                        : PTD5_KBI2P5
**              Pin signal                                 : UART2_CTS_N
**            Pin6                                         : Enabled
**              Pin                                        : PTD6_KBI2P6
**              Pin signal                                 : UART1_CTS_N
**            Pin7                                         : Disabled
**          Interrupts 
**            Keyboard request 
**              Interrupt                                  : Vkeyboard
**              Keyboard request interrupt                 : Disabled
**              ISR name                                   : drvCtsISR
**          Initialization 
**            Call Init method                             : yes
**     Contents  :
**         Init - void hwCts_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE hwCts. */

#include "hwCts.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      WOIS.c
**      Events.c
**      drvSys.c
**      drvExtFlash.c
**      bbu.c
**      drvAlarm.c
**      drvCts.c
**      drvRadio.c
**      crc.c
**      platform.c
**      stdafx.c
**      ui.c
**      system.c
**      radio.c
**      moisture.c
**      irrigation.c
**      datetime.c
**      config.c
**      drvEeprom.c
**      drvRtc.c
**      drvKeypad.c
**      drvSolenoid.c
**      drvMoist.c
**      drv.c
**      global.c
**      drvLed.c
**      drvLcd.c
**
** ###################################################################
ISR(drvCtsISR)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  //  Keyboard Interrupt Flag is cleared by writing a 1 to the
  //  KBACK control bit.
  // Example:   KBI2SC_KBACK = 0x01
}
*/

/*
** ===================================================================
**     Method      :  hwCts_Init (bean Init_KBI)
**
**     Description :
**         This method initializes registers of the KBI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void hwCts_Init(void)
{
  /* KBI2SC: KBIE=0 */
  clrReg8Bits(KBI2SC, 0x02);            
  /* KBI2ES: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0,KBEDG3=0,KBEDG2=0,KBEDG1=0,KBEDG0=0 */
  setReg8(KBI2ES, 0x00);                
  /* KBI2SC: KBIMOD=0 */
  clrReg8Bits(KBI2SC, 0x01);            
  /* KBI2PE: KBIPE7=0,KBIPE6=1,KBIPE5=1,KBIPE4=0,KBIPE3=0,KBIPE2=0,KBIPE1=1,KBIPE0=0 */
  setReg8(KBI2PE, 0x62);                
  /* KBI2SC: KBACK=1 */
  setReg8Bits(KBI2SC, 0x04);            
  /* KBI2SC: KBIE=0 */
  clrReg8Bits(KBI2SC, 0x02);            
}

/* END hwCts. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
