/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwCts.H
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : Init_KBI
**     Version   : Bean 01.022, Driver 01.09, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 5/14/2010, 1:20 PM
**     Abstract  :
**          This file implements the KBI (KBI2) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**          The KBI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.
**          The keyboard interrupt module (KBI) provides a few independently maskable 
**          external interrupts. When a port pin is enabled for keyboard interrupt 
**          function, an internal pullup/pulldown device is also enabled on the pin.

**     Settings  :
**          Bean name                                      : hwCts
**          Device                                         : KBI2
**          Settings 
**            Triggering sensitivity                       : edge
**          Pins 
**            Pin0                                         : Disabled
**            Pin1                                         : Enabled
**              Pin                                        : PTD1_KBI2P1_MOSI2
**              Pin signal                                 : XBEE_CTS_N
**            Pin2                                         : Disabled
**            Pin3                                         : Disabled
**            Pin4                                         : Disabled
**            Pin5                                         : Enabled
**              Pin                                        : PTD5_KBI2P5
**              Pin signal                                 : UART2_CTS_N
**            Pin6                                         : Enabled
**              Pin                                        : PTD6_KBI2P6
**              Pin signal                                 : UART1_CTS_N
**            Pin7                                         : Disabled
**          Interrupts 
**            Keyboard request 
**              Interrupt                                  : Vkeyboard
**              Keyboard request interrupt                 : Disabled
**              ISR name                                   : drvCtsISR
**          Initialization 
**            Call Init method                             : yes
**     Contents  :
**         Init - void hwCts_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __hwCts
#define __hwCts

/* MODULE hwCts. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "hwCpu.h"


/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see hwCts.c file for more information).
** ===================================================================
*/
__interrupt void drvCtsISR(void);

void hwCts_Init(void);
/*
** ===================================================================
**     Method      :  hwCts_Init (bean Init_KBI)
**
**     Description :
**         This method initializes registers of the KBI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END hwCts. */

#endif
/* ifndef __hwCts */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
