/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwI2c.C
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : InternalI2C
**     Version   : Bean 01.196, Driver 01.20, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 7/12/2011, 1:59 PM
**     Abstract  :
**          This bean encapsulates the internal I2C communication 
**          interface. The implementation of the interface is based 
**          on the Philips I2C-bus specification version 2.0. 
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible 
**              (see "Automatic stop condition" property)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
**     Comment   :
**         The I2C bus supports communication to the EEPROM used to store manufacturing data and system configuration.
**         
**         Automatic stop condition must be disabled.
**         
**     Settings  :
**         Serial channel              : IIC2
**
**         Protocol
**             Mode                    : MASTER
**             Auto stop condition     : no
**             SCL frequency           : 25165824 kHz
**
**         Initialization
**
**             Slave address           : 80
**             Bean function           : Enabled
**             Events                  : Enabled
**
**         Registers
**             Input buffer            : IIC2D     [0xFFFF986C]
**             Output buffer           : IIC2D     [0xFFFF986C]
**             Control register        : IIC2C1    [0xFFFF986A]
**             Status register         : IIC2S     [0xFFFF986B]
**             Baud setting reg.       : IIC2F     [0xFFFF9869]
**             Address register        : IIC2A     [0xFFFF9868]
**
**             Priority                : 
**
**         Used pins                   : 
**       ----------------------------------------------------------
**            Function    | On package |    Name
**       ----------------------------------------------------------
**              SDA       |     3      |  PTH7_SDA2
**              SCL       |     4      |  PTH6_SCL2
**       ----------------------------------------------------------
**     Contents  :
**         Enable    - byte hwI2c_Enable(void);
**         Disable   - byte hwI2c_Disable(void);
**         SendBlock - byte hwI2c_SendBlock(void* Ptr, word Siz, word *Snt);
**         RecvBlock - byte hwI2c_RecvBlock(void* Ptr, word Siz, word *Rcv);
**         SendStop  - byte hwI2c_SendStop(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE hwI2c. */


#include "hwI2c.h"

/*SerFlag bits*/
#define OVERRUN_ERR      0x01          /* Overrun error flag bit   */
#define WAIT_RX_CHAR     0x02          /* Wait for received char. flag bit (Master)  */
#define CHAR_IN_TX       0x04          /* Char is in TX buffer (Master)    */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer     */
#define FULL_TX          0x10          /* Full transmit buffer     */
#define IN_PROGRES       0x20          /* Communication is in progress (Master) */
#define FULL_RX          0x40          /* Full receive buffer      */
#define MSxSL            0x80          /* Master x Slave flag bit  */

/*SerFlag2 bits*/
#define ADDR_COMPLETE      0x01        /* 10-bit address transmission complete   */
#define REP_ADDR_COMPLETE  0x02        /* repeated address transmission complete */
#define GENERAL_CALL       0x04        /* General call flag */
#define ADDR_10            0x08        /* 10-bit addr flag */
#define ADDR_7             0x10        /* 7-bit addr flag */
static bool EnUser;                    /* Enable/Disable device */
static bool EnMode;                    /* Enable/Disable device in speed mode */
static word InpLenM;                   /* Length of input bufer's content */
static byte *InpPtrM;                  /* Pointer to input buffer for Master mode */
static word OutLenM;                   /* Length of output bufer's content */
static byte * OutPtrM;                 /* Pointer to output buffer for Master mode */
static word *PtrSndRcv;                /* Pointer to Snd/Rcv counter for SendBlock/RecvBlock */
volatile byte hwI2c_SerFlag;           /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Wait for received char. flag bit (Master) */
                                       /*       2 - Char is in TX buffer (Master) */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Master x Slave */
/*
** ===================================================================
**     Method      :  HWEnDi (bean InternalI2C)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*lint -save -e718 -e746 -e937 -e957 Disable MISRA rule (71) checking. */
static void HWEnDi(void)
{
  if (EnMode && EnUser) {              /* Enable device? */
    hwI2c_SerFlag &= ~0x7F;            /* Clear the status variable */
    IIC2C1_IICEN = 1;                  /* Enable device */
  }
  else {
    /* IIC2C1: IICEN=0,IICIE=0,MST=0,TX=0,TXAK=0,RSTA=0,??=0,??=0 */
    IIC2C1 = 0;                        /* Disable device */
  }
}
/*lint -restore */

/*
** ===================================================================
**     Method      :  hwI2c_SetHigh (bean InternalI2C)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the High speed mode. The method is 
**         called automatically as s part of the CPU SetHighSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwI2c_SetHigh(void)
{
  EnMode = TRUE;                       /* Set the flag "device enabled" in the actual speed CPU mode */
  HWEnDi();                            /* Enable/disable device according to the status flags */
}

/*
** ===================================================================
**     Method      :  hwI2c_SetSlow (bean InternalI2C)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the Slow speed mode. The method is 
**         called automatically as a part of the CPU SetSlowSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwI2c_SetSlow(void)
{
  EnMode = FALSE;                      /* Set the flag "device disabled" in the actual speed CPU mode */
  HWEnDi();                            /* Enable/disable device according to the status flags */
}

/*
** ===================================================================
**     Method      :  MainComm (bean InternalI2C)
**
**     Description :
**         The method services the communication in polling mode 
**         (interrupts disabled).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define RXAK 0x01
#define SRW  0x04
#define IBAL 0x10
#define IAAS 0x40
/*lint -save -e718 -e746 -e937 -e957 Disable MISRA rule (71) checking. */
static byte MainComm(void)
{
  word Tr;
  byte Status;                         /* Temporary variable for saving status register */

  *PtrSndRcv = 0;                      /* Clear Snd/Rcv counter */
  for(Tr=0; Tr<0x07D0;Tr++) {
    if(IIC2S_IICIF) {
      Status = IIC2S;                  /* Save status register */
      IIC2S_IICIF = 1;                 /* Clear interrupt flag */
      Tr = (byte)-1;                   /* Clear trials */
      if(IIC2C1_MST){                  /* Is device in master mode? */
        if(IIC2C1_TX){                 /* Is device in Tx mode? */
          if(Status & RXAK) {          /* NACK received? */
            OutLenM = 0;               /* No character for sending */
            InpLenM = 0;               /* No character for reception */
            hwI2c_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES); /* No character for sending or reception*/
            return ERR_BUSY;           /* Return with error */
          }
          else {
            if(OutLenM) {              /* Is any char. for transmitting? */
              OutLenM--;               /* Decrease number of chars for the transmit */
              IIC2D = *(OutPtrM)++;    /* Send character */
              (*PtrSndRcv)++;          /* Increment Snd counter */
            }
            else {
              if(InpLenM) {            /* Is any char. for reception? */
                if(InpLenM == 1) {     /* If only one char to receive */
                  IIC2C1_TXAK = 1;     /* then transmit ACK disable */
                }
                else {
                  IIC2C1_TXAK = 0;     /* else transmit ACK anable */
                }
                IIC2C1_TX = 0;         /* Switch to Rx mode */
                (void)IIC2D;           /* Dummy read character */
              }
              else {
                return ERR_OK;         /* Return without error */
              }
            }
          }
        }
        else {
          InpLenM--;                   /* Decrease number of chars for the receive */
          if(InpLenM) {                /* Is any char. for reception? */
            if(InpLenM == 1) {
              IIC2C1_TXAK = 1;         /* Transmit ACK disable */
            }
          }
          else {
            IIC2C1_MST = 0;            /* If no, switch device to slave mode (stop signal sent) */
          }
          *(InpPtrM)++ = IIC2D;        /* Receive character */
          (*PtrSndRcv)++;              /* Increment Rcv counter */
          if(!InpLenM) {               /* Is any char. for reception? */
            for(Tr=0x07D0;Tr!=0;Tr--) {
              if(!IIC2S_BUSY) {        /* Bus is busy? */
                return ERR_OK;         /* Return without error */
              }
            }
            return ERR_BUSOFF;         /* Return with error */
          }
        }
      }
      else {
        if(Status & IBAL) {            /* Arbitration lost? */
          OutLenM = 0;                 /* No character for sending */
          InpLenM = 0;                 /* No character for reception */
          hwI2c_SerFlag &= ~(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES); /* No character for sending or reception*/
          return ERR_ARBITR;           /* Return with error */
        }
      }
    }
  }
  return ERR_BUSOFF;                   /* Return with error */
}
/*lint -restore */

/*
** ===================================================================
**     Method      :  hwI2c_Enable (bean InternalI2C)
**
**     Description :
**         Enables I2C bean. Events may be generated
**         ("DisableEvent"/"EnableEvent").
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte hwI2c_Enable(void)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwI2c_Disable (bean InternalI2C)
**
**     Description :
**         Disables I2C bean. No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte hwI2c_Disable(void)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwI2c_SendBlock (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 0 to the I2C bus and then
**         writes the block of characters to the bus. The slave
**         address must be specified before, by the "SelectSlave" or
**         "SlaveSelect10" method or in bean initialization section,
**         "Target slave address init" property. If interrupt
**         service is enabled and the method returns ERR_OK, it
**         doesn't mean that transmission was successful. The state
**         of transmission is detectable by means of events
**         (OnTransmitData, OnError or OnArbitLost). Data to be send
**         is not copied to an internal buffer and remains in the
**         original location. Therefore the content of the buffer
**         should not be changed until the transmission is complete.
**         Event OnTransmitData can be used to detect the end of the
**         transmission.
**         When working as a SLAVE, this method writes a block of
**         characters to the internal output slave buffer and then,
**         after the master starts the communication, to the I2C bus.
**         If no character is ready for a transmission (internal
**         output slave buffer is empty), the "Empty character" will
**         be sent (see "Empty character" property). In SLAVE mode
**         the data are copied to an internal buffer, if specified
**         by "Output buffer size" property.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send.
**         Siz             - Size of the block.
**       * Snt             - Amount of data sent (moved to a buffer).
**                           In master mode, if interrupt support is
**                           enabled, the parameter always returns
**                           the same value as the parameter 'Siz' of
**                           this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge
**                           (only in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full. Some
**                           data has not been sent. (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
** ===================================================================
*/
byte hwI2c_SendBlock(void * Ptr,word Siz,word *Snt)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!Siz) {                          /* Test variable Size on zero */
    *Snt = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if(!EnUser) {                        /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if((InpLenM)||(hwI2c_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  PtrSndRcv = Snt;                     /* Safe Snd pointer */
  OutLenM = Siz;                       /* Set lenght of data */
  OutPtrM = (byte *)Ptr;               /* Save pointer to data for transmitting */
  IIC2C1_TX = 1;                       /* Set TX mode */
  if(IIC2C1_MST) {                     /* Is device in master mode? */
    IIC2C1_RSTA = 1;                   /* If yes then repeat start cycle generated */
  }
  else {
    IIC2C1_MST = 1;                    /* If no then start signal generated */
  }
  IIC2D = 0xA0;                        /* Send slave address */
  return (MainComm());                 /* Call main communication method and return */
}

/*
** ===================================================================
**     Method      :  hwI2c_RecvBlock (bean InternalI2C)
**
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address
**         bytes inclusive of R/W bit = 1 to the I2C bus, then reads
**         the block of characters from the bus and then sends the
**         stop condition. The slave address must be specified
**         before, by the "SelectSlave" or "SelectSlave10" method or
**         in bean initialization section, "Target slave address
**         init" property. If interrupt service is enabled and the
**         method returns ERR_OK, it doesn't mean that transmission
**         was finished successfully. The state of transmission must
**         be tested by means of events (OnReceiveData, OnError or
**         OnArbitLost). In case of successful transmission,
**         received data is ready after OnReceiveData event is
**         called. 
**         When working as a SLAVE, this method reads a block of
**         characters from the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block space for
**                           received data.
**         Siz             - The size of the block.
**       * Rcv             - Amount of received data. In master mode,
**                           if interrupt support is enabled, the
**                           parameter always returns the same value
**                           as the parameter 'Siz' of this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only
**                           in master mode and when interrupt
**                           service is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data.
**                           Only available data (or no data) has
**                           been returned  (slave mode only).
**                           ERR_OVERRUN - Overrun error was detected
**                           from last character or block receiving
**                           (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in
**                           master mode)
** ===================================================================
*/
byte hwI2c_RecvBlock(void* Ptr,word Siz,word *Rcv)
{
  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!Siz) {                          /* Test variable Size on zero */
    *Rcv = 0;
    return ERR_OK;                     /* If zero then OK */
  }
  if(!EnUser) {                        /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if((InpLenM)||(hwI2c_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  PtrSndRcv = Rcv;                     /* Safe Rcv pointer */
  InpLenM = Siz;                       /* Set lenght of data */
  InpPtrM = (byte *)Ptr;               /* Save pointer to data for reception */
  IIC2C1_TX = 1;                       /* Set TX mode */
  if(IIC2C1_MST) {                     /* Is device in master mode? */
    IIC2C1_RSTA = 1;                   /* If yes then repeat start cycle generated */
  }
  else {
    IIC2C1_MST = 1;                    /* If no then start signal generated */
  }
  IIC2D = 0xA1;                        /* Send slave address */
  return (MainComm());                 /* Call main communication method and return */
}

/*
** ===================================================================
**     Method      :  hwI2c_SendStop (bean InternalI2C)
**
**     Description :
**         If the "Automatic stop condition" property value is 'no',
**         this method sends a valid stop condition to the serial
**         data line of the I2C bus to terminate the communication
**         on the bus after using send methods. When the "Automatic
**         stop condition" property value is 'yes', this method is
**         not provided.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed - bus
**                           is busy
** ===================================================================
*/
byte hwI2c_SendStop(void)
{
  word Tr;

  if (!EnMode) {                       /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  }
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if((InpLenM)||(hwI2c_SerFlag&(CHAR_IN_TX|WAIT_RX_CHAR|IN_PROGRES))) { /* Is the bus busy */
    return ERR_BUSOFF;                 /* If yes then error */
  }
  IIC2C1_MST = 0;                      /* Set slave mode (send stop condition) */
  IIC2C1_TX = 0;                       /* Switch to Rx mode */
  for(Tr=0x07D0;Tr!=0;Tr--) {
    if(!IIC2S_BUSY) {                  /* Bus is busy? */
      return ERR_OK;                   /* Return without error */
    }
  }
  return ERR_BUSOFF;                   /* Return with error */
}

/*
** ===================================================================
**     Method      :  hwI2c_Init (bean InternalI2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwI2c_Init(void)
{
  hwI2c_SerFlag = 0x80;                /* Reset all flags */
  EnUser = TRUE;                       /* Enable device */
  /* IIC2F: MULT1=0,MULT0=0,ICR5=0,ICR4=1,ICR3=0,ICR2=0,ICR1=1,ICR0=1 */
  setReg8(IIC2F, 0x13);                 
  hwI2c_SetHigh();                     /* Initial speed CPU mode is high */
}


/* END hwI2c. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
