/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : hwRtc.C
**     Project   : WOIS
**     Processor : MCF51QE128CLK
**     Beantype  : TimerInt
**     Version   : Bean 02.154, Driver 01.14, CPU db: 3.00.052
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 7/12/2011, 1:59 PM
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : RTC (8-bit)
**         Compare name                : RTCmod
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**           Initial period/frequency
**             Xtal ticks              : 32768
**             microseconds            : 1000000
**             milliseconds            : 1000
**             seconds                 : 1
**             seconds (real)          : 1.0000000
**             Hz                      : 1
**
**         Slow speed mode
**             Prescaler               : divide-by-1
**           Initial period/frequency
**             Xtal ticks              : 32768
**             microseconds            : 1000000
**             milliseconds            : 1000
**             seconds                 : 1
**             seconds (real)          : 1.0000000
**             Hz                      : 1
**
**         Runtime setting             : modes (list of settings)
**            -----------------------------------------------------------------------
**            |  period  |     Prescaler      |        Real period [seconds]        |
**     --------    or    |-----------------------------------------------------------
**     | mode | freqency | high | low  | slow |    high    |    low     |    slow   |
**     ------------------------------------------------------------------------------
**     |  0   |  1Hz     | 1    | -    | 1    | 1.0000000  | -          | 1.0000000 |
**     |  1   |  32Hz    | 1    | -    | 1    | 0.0312500  | -          | 0.0312500 |
**     ------------------------------------------------------------------------------
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : RTCCNT    [0xFFFF9831]
**              Mode                   : RTCSC     [0xFFFF9830]
**              Run                    : RTCSC     [0xFFFF9830]
**              Prescaler              : RTCSC     [0xFFFF9830]
**
**         Compare registers
**              Compare                : RTCMOD    [0xFFFF9832]
**
**         Flip-flop registers
**     Contents  :
**         SetPeriodMode - byte hwRtc_SetPeriodMode(byte Mode);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE hwRtc. */

#include "Events.h"
#include "PE_Error.h"
#include "hwRtc.h"

static bool EnUser;                    /* Enable device by user */
static byte TMode;                     /* Number of actual timer modes */

/* Table of compare register values for High speed CPU mode */
static const  byte HighComp[2] = { 31, 0 };
/* Internal method prototypes */


/*
** ===================================================================
**     Method      :  HWEnDi (bean TimerInt)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {
    /* RTCSC: RTIF=1,RTCLKS=1,RTIE=1,RTCPS=1 */
    setReg8(RTCSC, 0xB1);              /* Run RTC - select clock source; set frequency and enable interrupt */ 
  } else {
    /* RTCSC: RTCPS=0 */
    clrReg8Bits(RTCSC, 0x0F);          /* Stop counter (RTCPS[0:3] = 000) */ 
  }
}

/*
** ===================================================================
**     Method      :  hwRtc_SetPeriodMode (bean TimerInt)
**
**     Description :
**         Switches the bean to a specified mode (changes the period/frequency
**         using the mode values). This method reduces the time needed
**         for setting of a new period value. This method can be used only when
**         a list of possible period settings is specified at design time.
**         Each of these settings constitutes a mode and Processor Expert
**         assigns them a mode identifier. The prescaler and compare values
**         corresponding to each mode are calculated at design time.
**         Modes can be switched at runtime just by referring to a mode
**         identifier. No run-time calculations are performed, all the
**         calculations are performed at design time. The modes and mode
**         identifiers may be found in the include file *.h.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mode       - Mode to switch to (0 to 1)
**                         0.   1Hz
**                         1.   32Hz
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_VALUE - Value out of range,
**                           requested timing mode is not defined
** ===================================================================
*/
byte hwRtc_SetPeriodMode(byte Mode)
{
  bool TmrRun;                         /* Temporary flag enable/disable */

  if (Mode > 0x01) {                   /* Is a values of mode identifier out of range? */
    return ERR_VALUE;                  /* If yes then error */
  }
  TmrRun = EnUser;                     /* Store actual device state */
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  TMode = Mode;                        /* Store given mode identifier to the variable TMode */
  hwRtc_SetCV((byte)HighComp[Mode]);   /* Set compare value for new period */
  /* There is not necessary to set prescaler because the presc. is the same for all possible generated periods */
  if (TmrRun) {                        /* Was the device disabled? */
    EnUser = TRUE;                     /* If yes set flag "device enabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  hwRtc_SetHigh (bean TimerInt)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the High speed mode. The method is 
**         called automatically as s part of the CPU SetHighSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwRtc_SetHigh(void)
{
  RTCMOD = RTCMOD;                     /* Reset HW counter */
  HWEnDi();
}

/*
** ===================================================================
**     Method      :  hwRtc_SetSlow (bean TimerInt)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the Slow speed mode. The method is 
**         called automatically as a part of the CPU SetSlowSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwRtc_SetSlow(void)
{
  RTCMOD = RTCMOD;                     /* Reset HW counter */
  HWEnDi();
}

/*
** ===================================================================
**     Method      :  hwRtc_Init (bean TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void hwRtc_Init(void)
{
  /* RTCSC: RTIF=0,RTCLKS=0,RTIE=0,RTCPS=0 */
  setReg8(RTCSC, 0x00);                /* Stop HW */ 
  EnUser = TRUE;                       /* Enable device */
  TMode = 0x00;                        /* Actual timer modes = 0 */
  hwRtc_SetCV(0x1F);                   /* Inicialize appropriate value to the compare/modulo/reload register */
  hwRtc_SetHigh();                     /* Initial speed CPU mode is high */
}


/*
** ===================================================================
**     Method      :  hwRtc_Interrupt (bean TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(hwRtc_Interrupt)
{
  /* RTCSC: RTIF=1 */
  setReg8Bits(RTCSC, 0x80);            /* Reset real-time counter request flag */ 
  hwRtc_OnInterrupt();                 /* Invoke user event */
}



/* END hwRtc. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
